### ISSUE TITLE
`mu` support for EKS / Kubernetes

### ISSUE THREAD

**Issue by timbaileyjones** [stelligent/mu#228] opened 2017-11-29 16:50 UTC
Would it make sense to extend `mu` into Kubernetes?

New from re:invent 2017: 
https://aws.amazon.com/blogs/aws/amazon-elastic-container-service-for-kubernetes/

EDIT: changed "ECS" to "EKS" in the title

**Comment by cplee** [comment] 2017-12-07 07:52
duplicate of #233

**Closed by cplee** 2017-12-07 07:52 UTC
Labels: duplicate

**Comment by timbaileyjones** [comment] 2017-12-07 14:12
yes, but 228 came before 233. 💫
